spatial <- read.csv(file="changes-1-oneneighbor.csv",head=TRUE,sep=",")
spatial1 <- read.csv(file="changes-5-oneneighbor.csv",head=TRUE,sep=",")
spatial2 <- read.csv(file="changes-7-oneneighbor.csv",head=TRUE,sep=",")
spatial3 <- read.csv(file="changes-10-oneneighbor.csv",head=TRUE,sep=",")
plot_colors <- rainbow(4)
matplot(c(0:300), rowMeans(spatial3), type="l", lty = 1, xlab = "time", ylab = "changes")
with(spatial2, lines(c(0:300), rowMeans(spatial2), col = plot_colors[1]))
with(spatial1, lines(c(0:300), rowMeans(spatial1), col = plot_colors[2]))
with(spatial, lines(c(0:300), rowMeans(spatial), col = plot_colors[3]))
legend("topright", legend = c("1", "0.7", "0.5", "0.1"), col=1:4, pch=1)
